# Generated by Django 5.2 on 2025-11-26 17:56

import dashboard.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0014_alter_faculty_class_type_alter_student_class_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_expertise', models.CharField(blank=True, default='Field of Expertise', max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, default='Skills', max_length=1000, null=True)),
                ('level_of_competence', models.CharField(blank=True, default='Level of Competence', max_length=1000, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_expertise', to='userManagement.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='Job Title', max_length=1000, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='Job Location', max_length=1000, null=True)),
                ('required_skills', models.CharField(blank=True, default='Skills', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='Job Description', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobListing', to='userManagement.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_summary', models.TextField(blank=True, default='Project Description', null=True)),
                ('skills_demonstrated', models.TextField(blank=True, default='Skills Demonstrated', null=True)),
                ('field_of_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.fieldofexpertise')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload image files (JPG, PNG, GIF). Max size: 10MB', null=True, upload_to=dashboard.models.upload_to_pictures, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='dashboard.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='files/default.txt', help_text='Upload documents (PDF, DOC, DOCX, TXT, ZIP). Max size: 10MB', null=True, upload_to=dashboard.models.upload_to_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip'])])),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.project')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Upload video files (MP4, AVI, MOV). Max size: 100MB', null=True, upload_to=dashboard.models.upload_to_videos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
