# Generated by Django 5.0.6 on 2026-03-24 00:12

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_fieldofexpertise_order_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_n_tools_used',
            field=models.TextField(blank=True, default='Technologies and Tools Used', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='what_i_learnd',
            field=models.TextField(blank=True, default='What I Learned', null=True, validators=[dashboard.models.validate_max_500_words]),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, help_text='Upload documents (PDF, DOC, DOCX, TXT, ZIP, XLSX). Max size: 10MB', null=True, upload_to=dashboard.models.upload_to_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_summary',
            field=models.TextField(blank=True, default='Project Description', null=True, validators=[dashboard.models.validate_max_500_words]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video files (MP4, AVI, MOV). Max size: 1000MB', null=True, upload_to=dashboard.models.upload_to_videos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
    ]
