# Generated by Django 5.0.6 on 2026-04-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_savedstudent_interview'),
        ('userManagement', '0017_remove_portfolio_bio_portfolio_about_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Received'), ('not_selected', 'Not Selected')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='dashboard.joblisting')),
                ('student_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='userManagement.portfolio')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student_portfolio', 'job_listing')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='dashboard.joblisting')),
                ('student_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='userManagement.portfolio')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('student_portfolio', 'job_listing')},
            },
        ),
    ]
