# Generated by Django 5.0.6 on 2026-04-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofexpertise',
            options={'ordering': ['portfolio', 'id']},
        ),
        migrations.RemoveField(
            model_name='fieldofexpertise',
            name='order',
        ),
    ]
