# Generated by Django 5.2 on 2025-11-26 18:10

import dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, help_text='Upload documents (PDF, DOC, DOCX, TXT, ZIP). Max size: 10MB', null=True, upload_to=dashboard.models.upload_to_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip'])]),
        ),
    ]
