# Generated by Django 5.0.6 on 2026-03-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_tech_n_tools_used_project_what_i_learnd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
