# Generated by Django 5.0.6 on 2026-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_jobapplication_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Received'), ('accepted', 'Offer Accepted'), ('not_selected', 'Not Selected')], default='pending', max_length=30),
        ),
    ]
