# Generated by Django 5.2 on 2025-06-10 22:07

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Bio', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=100, null=True, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('current_course', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('current_year', models.CharField(default='What Course Year Are You In?', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_expertise', models.CharField(blank=True, default='Field of Expertise', max_length=1000, null=True)),
                ('skills', models.CharField(blank=True, default='Skills', max_length=1000, null=True)),
                ('level_of_competence', models.CharField(blank=True, default='Level of Competence', max_length=1000, null=True)),
                ('portfolio', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_expertise', to='userManagement.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_description', models.TextField(blank=True, default='Project Description', null=True)),
                ('skills_demonstrated', models.TextField(blank=True, default='Skills Demonstrated', null=True)),
                ('field_of_expertise', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='userManagement.fieldofexpertise')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureUpload', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='userManagement.project')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileUpload', models.FileField(blank=True, null=True, upload_to='files/')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='userManagement.project')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='userManagement.student'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUpload', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='userManagement.project')),
            ],
        ),
    ]
