# Generated by Django 5.2 on 2025-06-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_remove_student_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
