# Generated by Django 5.2 on 2025-06-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
