# Generated by Django 5.2 on 2025-06-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_alter_project_options_alter_student_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
    ]
