# Generated by Django 5.2 on 2025-06-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_remove_student_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
    ]
