# Generated by Django 5.2 on 2025-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_remove_student_fname_remove_student_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='vatar',
            field=models.ImageField(default='avatar.jpg', upload_to='media/pictures'),
        ),
    ]
