# Generated by Django 5.2 on 2025-06-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_portfolio_vatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='vatar',
            new_name='avatar',
        ),
    ]
