# Generated by Django 5.2 on 2025-06-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0008_rename_vatar_portfolio_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='avatar',
        ),
    ]
