# Generated by Django 5.2 on 2025-06-16 12:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userManagement', '0009_remove_portfolio_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('professor_of', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty Members',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Bio', null=True)),
                ('faculty', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='userManagement.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='Field of Expertise', max_length=1000, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='Job Location', max_length=1000, null=True)),
                ('required_skills', models.CharField(blank=True, default='Skills', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='Job Description', null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_expertise', to='userManagement.profile')),
            ],
        ),
    ]
