# Generated by Django 5.2 on 2025-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0010_faculty_profile_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='class_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='faculty', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='class_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=20),
        ),
    ]
