# Generated by Django 5.2 on 2025-06-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_alter_profile_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='field_of_expertise',
        ),
        migrations.RemoveField(
            model_name='files',
            name='project',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='project',
        ),
        migrations.RemoveField(
            model_name='video',
            name='project',
        ),
        migrations.DeleteModel(
            name='FieldOfExpertise',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
