# Generated by Django 5.2 on 2025-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0013_remove_project_field_of_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='class_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='Faculty', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='Student', max_length=20),
        ),
    ]
