# Generated by Django 5.0.6 on 2026-03-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='application_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='job_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
