# Generated by Django 5.2 on 2026-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0016_portfolio_application_updates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='bio',
            new_name='about_me',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='what_I_bring',
            field=models.TextField(blank=True, default=''),
        ),
    ]
